import Head from 'next/head'

import Banner from 'components/banner'
import Navbar from 'components/navbar'

import styles from 'styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Netflix</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar username="khangviet1996@gmail.com" />

      <Banner
        title="Clifford the red dog"
        subtitle="A very cute dog"
        imgUrl="/static/clifford.webp"
      />
    </div>
  )
}
