import Head from 'next/head'

import Banner from 'components/banner'
import Navbar from 'components/navbar'

import SectionCards from 'components/card/section-cards'

import { getVideos, getPopularVideos } from 'lib/videos'

import styles from 'styles/Home.module.css'

export async function getServerSideProps() {
  const disneyVideos = await getVideos('disney')
  const travelVideos = await getVideos('travel')
  const productivityVideos = await getVideos('productivity')
  const popularVideos = await getPopularVideos()

  return {
    props: { disneyVideos, travelVideos, productivityVideos, popularVideos },
  }
}

export default function Home(props) {
  const { disneyVideos, travelVideos, productivityVideos, popularVideos } =
    props

  return (
    <div className={styles.container}>
      <Head>
        <title>Netflix</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />

      <Banner
        title="Clifford the red dog"
        subtitle="A very cute dog"
        imgUrl="/static/clifford.webp"
      />

      <SectionCards header="Disney" size="large" videos={disneyVideos} />

      <SectionCards header="Travel" size="medium" videos={travelVideos} />

      <SectionCards
        header="Productivity"
        size="small"
        videos={productivityVideos}
      />

      <SectionCards header="Popular" size="medium" videos={popularVideos} />
    </div>
  )
}
